// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Library is the predicate function for library builders.
type Library func(*sql.Selector)

// Video is the predicate function for video builders.
type Video func(*sql.Selector)
