// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/altierawr/vstreamer/ent/audiocodec"
	"github.com/altierawr/vstreamer/ent/audiotrack"
	"github.com/altierawr/vstreamer/ent/playsessionmedia"
	"github.com/altierawr/vstreamer/ent/predicate"
	"github.com/altierawr/vstreamer/ent/stream"
)

// AudioCodecQuery is the builder for querying AudioCodec entities.
type AudioCodecQuery struct {
	config
	ctx                  *QueryContext
	order                []audiocodec.OrderOption
	inters               []Interceptor
	predicates           []predicate.AudioCodec
	withStreams          *StreamQuery
	withAudioTracks      *AudioTrackQuery
	withMedia            *PlaySessionMediaQuery
	withFKs              bool
	modifiers            []func(*sql.Selector)
	loadTotal            []func(context.Context, []*AudioCodec) error
	withNamedStreams     map[string]*StreamQuery
	withNamedAudioTracks map[string]*AudioTrackQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AudioCodecQuery builder.
func (acq *AudioCodecQuery) Where(ps ...predicate.AudioCodec) *AudioCodecQuery {
	acq.predicates = append(acq.predicates, ps...)
	return acq
}

// Limit the number of records to be returned by this query.
func (acq *AudioCodecQuery) Limit(limit int) *AudioCodecQuery {
	acq.ctx.Limit = &limit
	return acq
}

// Offset to start from.
func (acq *AudioCodecQuery) Offset(offset int) *AudioCodecQuery {
	acq.ctx.Offset = &offset
	return acq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (acq *AudioCodecQuery) Unique(unique bool) *AudioCodecQuery {
	acq.ctx.Unique = &unique
	return acq
}

// Order specifies how the records should be ordered.
func (acq *AudioCodecQuery) Order(o ...audiocodec.OrderOption) *AudioCodecQuery {
	acq.order = append(acq.order, o...)
	return acq
}

// QueryStreams chains the current query on the "streams" edge.
func (acq *AudioCodecQuery) QueryStreams() *StreamQuery {
	query := (&StreamClient{config: acq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := acq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := acq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(audiocodec.Table, audiocodec.FieldID, selector),
			sqlgraph.To(stream.Table, stream.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, audiocodec.StreamsTable, audiocodec.StreamsColumn),
		)
		fromU = sqlgraph.SetNeighbors(acq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAudioTracks chains the current query on the "audio_tracks" edge.
func (acq *AudioCodecQuery) QueryAudioTracks() *AudioTrackQuery {
	query := (&AudioTrackClient{config: acq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := acq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := acq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(audiocodec.Table, audiocodec.FieldID, selector),
			sqlgraph.To(audiotrack.Table, audiotrack.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, audiocodec.AudioTracksTable, audiocodec.AudioTracksPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(acq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMedia chains the current query on the "media" edge.
func (acq *AudioCodecQuery) QueryMedia() *PlaySessionMediaQuery {
	query := (&PlaySessionMediaClient{config: acq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := acq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := acq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(audiocodec.Table, audiocodec.FieldID, selector),
			sqlgraph.To(playsessionmedia.Table, playsessionmedia.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, audiocodec.MediaTable, audiocodec.MediaColumn),
		)
		fromU = sqlgraph.SetNeighbors(acq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AudioCodec entity from the query.
// Returns a *NotFoundError when no AudioCodec was found.
func (acq *AudioCodecQuery) First(ctx context.Context) (*AudioCodec, error) {
	nodes, err := acq.Limit(1).All(setContextOp(ctx, acq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{audiocodec.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (acq *AudioCodecQuery) FirstX(ctx context.Context) *AudioCodec {
	node, err := acq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AudioCodec ID from the query.
// Returns a *NotFoundError when no AudioCodec ID was found.
func (acq *AudioCodecQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = acq.Limit(1).IDs(setContextOp(ctx, acq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{audiocodec.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (acq *AudioCodecQuery) FirstIDX(ctx context.Context) int {
	id, err := acq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AudioCodec entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AudioCodec entity is found.
// Returns a *NotFoundError when no AudioCodec entities are found.
func (acq *AudioCodecQuery) Only(ctx context.Context) (*AudioCodec, error) {
	nodes, err := acq.Limit(2).All(setContextOp(ctx, acq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{audiocodec.Label}
	default:
		return nil, &NotSingularError{audiocodec.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (acq *AudioCodecQuery) OnlyX(ctx context.Context) *AudioCodec {
	node, err := acq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AudioCodec ID in the query.
// Returns a *NotSingularError when more than one AudioCodec ID is found.
// Returns a *NotFoundError when no entities are found.
func (acq *AudioCodecQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = acq.Limit(2).IDs(setContextOp(ctx, acq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{audiocodec.Label}
	default:
		err = &NotSingularError{audiocodec.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (acq *AudioCodecQuery) OnlyIDX(ctx context.Context) int {
	id, err := acq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AudioCodecs.
func (acq *AudioCodecQuery) All(ctx context.Context) ([]*AudioCodec, error) {
	ctx = setContextOp(ctx, acq.ctx, "All")
	if err := acq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AudioCodec, *AudioCodecQuery]()
	return withInterceptors[[]*AudioCodec](ctx, acq, qr, acq.inters)
}

// AllX is like All, but panics if an error occurs.
func (acq *AudioCodecQuery) AllX(ctx context.Context) []*AudioCodec {
	nodes, err := acq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AudioCodec IDs.
func (acq *AudioCodecQuery) IDs(ctx context.Context) (ids []int, err error) {
	if acq.ctx.Unique == nil && acq.path != nil {
		acq.Unique(true)
	}
	ctx = setContextOp(ctx, acq.ctx, "IDs")
	if err = acq.Select(audiocodec.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (acq *AudioCodecQuery) IDsX(ctx context.Context) []int {
	ids, err := acq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (acq *AudioCodecQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, acq.ctx, "Count")
	if err := acq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, acq, querierCount[*AudioCodecQuery](), acq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (acq *AudioCodecQuery) CountX(ctx context.Context) int {
	count, err := acq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (acq *AudioCodecQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, acq.ctx, "Exist")
	switch _, err := acq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (acq *AudioCodecQuery) ExistX(ctx context.Context) bool {
	exist, err := acq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AudioCodecQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (acq *AudioCodecQuery) Clone() *AudioCodecQuery {
	if acq == nil {
		return nil
	}
	return &AudioCodecQuery{
		config:          acq.config,
		ctx:             acq.ctx.Clone(),
		order:           append([]audiocodec.OrderOption{}, acq.order...),
		inters:          append([]Interceptor{}, acq.inters...),
		predicates:      append([]predicate.AudioCodec{}, acq.predicates...),
		withStreams:     acq.withStreams.Clone(),
		withAudioTracks: acq.withAudioTracks.Clone(),
		withMedia:       acq.withMedia.Clone(),
		// clone intermediate query.
		sql:  acq.sql.Clone(),
		path: acq.path,
	}
}

// WithStreams tells the query-builder to eager-load the nodes that are connected to
// the "streams" edge. The optional arguments are used to configure the query builder of the edge.
func (acq *AudioCodecQuery) WithStreams(opts ...func(*StreamQuery)) *AudioCodecQuery {
	query := (&StreamClient{config: acq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	acq.withStreams = query
	return acq
}

// WithAudioTracks tells the query-builder to eager-load the nodes that are connected to
// the "audio_tracks" edge. The optional arguments are used to configure the query builder of the edge.
func (acq *AudioCodecQuery) WithAudioTracks(opts ...func(*AudioTrackQuery)) *AudioCodecQuery {
	query := (&AudioTrackClient{config: acq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	acq.withAudioTracks = query
	return acq
}

// WithMedia tells the query-builder to eager-load the nodes that are connected to
// the "media" edge. The optional arguments are used to configure the query builder of the edge.
func (acq *AudioCodecQuery) WithMedia(opts ...func(*PlaySessionMediaQuery)) *AudioCodecQuery {
	query := (&PlaySessionMediaClient{config: acq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	acq.withMedia = query
	return acq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AudioCodec.Query().
//		GroupBy(audiocodec.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (acq *AudioCodecQuery) GroupBy(field string, fields ...string) *AudioCodecGroupBy {
	acq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AudioCodecGroupBy{build: acq}
	grbuild.flds = &acq.ctx.Fields
	grbuild.label = audiocodec.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.AudioCodec.Query().
//		Select(audiocodec.FieldName).
//		Scan(ctx, &v)
func (acq *AudioCodecQuery) Select(fields ...string) *AudioCodecSelect {
	acq.ctx.Fields = append(acq.ctx.Fields, fields...)
	sbuild := &AudioCodecSelect{AudioCodecQuery: acq}
	sbuild.label = audiocodec.Label
	sbuild.flds, sbuild.scan = &acq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AudioCodecSelect configured with the given aggregations.
func (acq *AudioCodecQuery) Aggregate(fns ...AggregateFunc) *AudioCodecSelect {
	return acq.Select().Aggregate(fns...)
}

func (acq *AudioCodecQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range acq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, acq); err != nil {
				return err
			}
		}
	}
	for _, f := range acq.ctx.Fields {
		if !audiocodec.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if acq.path != nil {
		prev, err := acq.path(ctx)
		if err != nil {
			return err
		}
		acq.sql = prev
	}
	return nil
}

func (acq *AudioCodecQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AudioCodec, error) {
	var (
		nodes       = []*AudioCodec{}
		withFKs     = acq.withFKs
		_spec       = acq.querySpec()
		loadedTypes = [3]bool{
			acq.withStreams != nil,
			acq.withAudioTracks != nil,
			acq.withMedia != nil,
		}
	)
	if acq.withMedia != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, audiocodec.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AudioCodec).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AudioCodec{config: acq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(acq.modifiers) > 0 {
		_spec.Modifiers = acq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, acq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := acq.withStreams; query != nil {
		if err := acq.loadStreams(ctx, query, nodes,
			func(n *AudioCodec) { n.Edges.Streams = []*Stream{} },
			func(n *AudioCodec, e *Stream) { n.Edges.Streams = append(n.Edges.Streams, e) }); err != nil {
			return nil, err
		}
	}
	if query := acq.withAudioTracks; query != nil {
		if err := acq.loadAudioTracks(ctx, query, nodes,
			func(n *AudioCodec) { n.Edges.AudioTracks = []*AudioTrack{} },
			func(n *AudioCodec, e *AudioTrack) { n.Edges.AudioTracks = append(n.Edges.AudioTracks, e) }); err != nil {
			return nil, err
		}
	}
	if query := acq.withMedia; query != nil {
		if err := acq.loadMedia(ctx, query, nodes, nil,
			func(n *AudioCodec, e *PlaySessionMedia) { n.Edges.Media = e }); err != nil {
			return nil, err
		}
	}
	for name, query := range acq.withNamedStreams {
		if err := acq.loadStreams(ctx, query, nodes,
			func(n *AudioCodec) { n.appendNamedStreams(name) },
			func(n *AudioCodec, e *Stream) { n.appendNamedStreams(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range acq.withNamedAudioTracks {
		if err := acq.loadAudioTracks(ctx, query, nodes,
			func(n *AudioCodec) { n.appendNamedAudioTracks(name) },
			func(n *AudioCodec, e *AudioTrack) { n.appendNamedAudioTracks(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range acq.loadTotal {
		if err := acq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (acq *AudioCodecQuery) loadStreams(ctx context.Context, query *StreamQuery, nodes []*AudioCodec, init func(*AudioCodec), assign func(*AudioCodec, *Stream)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*AudioCodec)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Stream(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(audiocodec.StreamsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.audio_codec_streams
		if fk == nil {
			return fmt.Errorf(`foreign-key "audio_codec_streams" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "audio_codec_streams" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (acq *AudioCodecQuery) loadAudioTracks(ctx context.Context, query *AudioTrackQuery, nodes []*AudioCodec, init func(*AudioCodec), assign func(*AudioCodec, *AudioTrack)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*AudioCodec)
	nids := make(map[int]map[*AudioCodec]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(audiocodec.AudioTracksTable)
		s.Join(joinT).On(s.C(audiotrack.FieldID), joinT.C(audiocodec.AudioTracksPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(audiocodec.AudioTracksPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(audiocodec.AudioTracksPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*AudioCodec]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*AudioTrack](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "audio_tracks" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (acq *AudioCodecQuery) loadMedia(ctx context.Context, query *PlaySessionMediaQuery, nodes []*AudioCodec, init func(*AudioCodec), assign func(*AudioCodec, *PlaySessionMedia)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*AudioCodec)
	for i := range nodes {
		if nodes[i].play_session_media_audio_codecs == nil {
			continue
		}
		fk := *nodes[i].play_session_media_audio_codecs
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(playsessionmedia.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "play_session_media_audio_codecs" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (acq *AudioCodecQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := acq.querySpec()
	if len(acq.modifiers) > 0 {
		_spec.Modifiers = acq.modifiers
	}
	_spec.Node.Columns = acq.ctx.Fields
	if len(acq.ctx.Fields) > 0 {
		_spec.Unique = acq.ctx.Unique != nil && *acq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, acq.driver, _spec)
}

func (acq *AudioCodecQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(audiocodec.Table, audiocodec.Columns, sqlgraph.NewFieldSpec(audiocodec.FieldID, field.TypeInt))
	_spec.From = acq.sql
	if unique := acq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if acq.path != nil {
		_spec.Unique = true
	}
	if fields := acq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, audiocodec.FieldID)
		for i := range fields {
			if fields[i] != audiocodec.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := acq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := acq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := acq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := acq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (acq *AudioCodecQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(acq.driver.Dialect())
	t1 := builder.Table(audiocodec.Table)
	columns := acq.ctx.Fields
	if len(columns) == 0 {
		columns = audiocodec.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if acq.sql != nil {
		selector = acq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if acq.ctx.Unique != nil && *acq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range acq.predicates {
		p(selector)
	}
	for _, p := range acq.order {
		p(selector)
	}
	if offset := acq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := acq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedStreams tells the query-builder to eager-load the nodes that are connected to the "streams"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (acq *AudioCodecQuery) WithNamedStreams(name string, opts ...func(*StreamQuery)) *AudioCodecQuery {
	query := (&StreamClient{config: acq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if acq.withNamedStreams == nil {
		acq.withNamedStreams = make(map[string]*StreamQuery)
	}
	acq.withNamedStreams[name] = query
	return acq
}

// WithNamedAudioTracks tells the query-builder to eager-load the nodes that are connected to the "audio_tracks"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (acq *AudioCodecQuery) WithNamedAudioTracks(name string, opts ...func(*AudioTrackQuery)) *AudioCodecQuery {
	query := (&AudioTrackClient{config: acq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if acq.withNamedAudioTracks == nil {
		acq.withNamedAudioTracks = make(map[string]*AudioTrackQuery)
	}
	acq.withNamedAudioTracks[name] = query
	return acq
}

// AudioCodecGroupBy is the group-by builder for AudioCodec entities.
type AudioCodecGroupBy struct {
	selector
	build *AudioCodecQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (acgb *AudioCodecGroupBy) Aggregate(fns ...AggregateFunc) *AudioCodecGroupBy {
	acgb.fns = append(acgb.fns, fns...)
	return acgb
}

// Scan applies the selector query and scans the result into the given value.
func (acgb *AudioCodecGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, acgb.build.ctx, "GroupBy")
	if err := acgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AudioCodecQuery, *AudioCodecGroupBy](ctx, acgb.build, acgb, acgb.build.inters, v)
}

func (acgb *AudioCodecGroupBy) sqlScan(ctx context.Context, root *AudioCodecQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(acgb.fns))
	for _, fn := range acgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*acgb.flds)+len(acgb.fns))
		for _, f := range *acgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*acgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := acgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AudioCodecSelect is the builder for selecting fields of AudioCodec entities.
type AudioCodecSelect struct {
	*AudioCodecQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (acs *AudioCodecSelect) Aggregate(fns ...AggregateFunc) *AudioCodecSelect {
	acs.fns = append(acs.fns, fns...)
	return acs
}

// Scan applies the selector query and scans the result into the given value.
func (acs *AudioCodecSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, acs.ctx, "Select")
	if err := acs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AudioCodecQuery, *AudioCodecSelect](ctx, acs.AudioCodecQuery, acs, acs.inters, v)
}

func (acs *AudioCodecSelect) sqlScan(ctx context.Context, root *AudioCodecQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(acs.fns))
	for _, fn := range acs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*acs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := acs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
