// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"

	"entgo.io/contrib/entgql"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/errcode"
	"github.com/altierawr/vstreamer/ent/library"
	"github.com/altierawr/vstreamer/ent/playsession"
	"github.com/altierawr/vstreamer/ent/video"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Common entgql types.
type (
	Cursor         = entgql.Cursor[int]
	PageInfo       = entgql.PageInfo[int]
	OrderDirection = entgql.OrderDirection
)

func orderFunc(o OrderDirection, field string) func(*sql.Selector) {
	if o == entgql.OrderDirectionDesc {
		return Desc(field)
	}
	return Asc(field)
}

const errInvalidPagination = "INVALID_PAGINATION"

func validateFirstLast(first, last *int) (err *gqlerror.Error) {
	switch {
	case first != nil && last != nil:
		err = &gqlerror.Error{
			Message: "Passing both `first` and `last` to paginate a connection is not supported.",
		}
	case first != nil && *first < 0:
		err = &gqlerror.Error{
			Message: "`first` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	case last != nil && *last < 0:
		err = &gqlerror.Error{
			Message: "`last` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	}
	return err
}

func collectedField(ctx context.Context, path ...string) *graphql.CollectedField {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return nil
	}
	field := fc.Field
	oc := graphql.GetOperationContext(ctx)
walk:
	for _, name := range path {
		for _, f := range graphql.CollectFields(oc, field.Selections, nil) {
			if f.Alias == name {
				field = f
				continue walk
			}
		}
		return nil
	}
	return &field
}

func hasCollectedField(ctx context.Context, path ...string) bool {
	if graphql.GetFieldContext(ctx) == nil {
		return true
	}
	return collectedField(ctx, path...) != nil
}

const (
	edgesField      = "edges"
	nodeField       = "node"
	pageInfoField   = "pageInfo"
	totalCountField = "totalCount"
)

func paginateLimit(first, last *int) int {
	var limit int
	if first != nil {
		limit = *first + 1
	} else if last != nil {
		limit = *last + 1
	}
	return limit
}

// LibraryEdge is the edge representation of Library.
type LibraryEdge struct {
	Node   *Library `json:"node"`
	Cursor Cursor   `json:"cursor"`
}

// LibraryConnection is the connection containing edges to Library.
type LibraryConnection struct {
	Edges      []*LibraryEdge `json:"edges"`
	PageInfo   PageInfo       `json:"pageInfo"`
	TotalCount int            `json:"totalCount"`
}

func (c *LibraryConnection) build(nodes []*Library, pager *libraryPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *Library
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *Library {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *Library {
			return nodes[i]
		}
	}
	c.Edges = make([]*LibraryEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &LibraryEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// LibraryPaginateOption enables pagination customization.
type LibraryPaginateOption func(*libraryPager) error

// WithLibraryOrder configures pagination ordering.
func WithLibraryOrder(order *LibraryOrder) LibraryPaginateOption {
	if order == nil {
		order = DefaultLibraryOrder
	}
	o := *order
	return func(pager *libraryPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultLibraryOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithLibraryFilter configures pagination filter.
func WithLibraryFilter(filter func(*LibraryQuery) (*LibraryQuery, error)) LibraryPaginateOption {
	return func(pager *libraryPager) error {
		if filter == nil {
			return errors.New("LibraryQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type libraryPager struct {
	reverse bool
	order   *LibraryOrder
	filter  func(*LibraryQuery) (*LibraryQuery, error)
}

func newLibraryPager(opts []LibraryPaginateOption, reverse bool) (*libraryPager, error) {
	pager := &libraryPager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultLibraryOrder
	}
	return pager, nil
}

func (p *libraryPager) applyFilter(query *LibraryQuery) (*LibraryQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *libraryPager) toCursor(l *Library) Cursor {
	return p.order.Field.toCursor(l)
}

func (p *libraryPager) applyCursors(query *LibraryQuery, after, before *Cursor) (*LibraryQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultLibraryOrder.Field.column, p.order.Field.column, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *libraryPager) applyOrder(query *LibraryQuery) *LibraryQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(p.order.Field.toTerm(direction.OrderTermOption()))
	if p.order.Field != DefaultLibraryOrder.Field {
		query = query.Order(DefaultLibraryOrder.Field.toTerm(direction.OrderTermOption()))
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return query
}

func (p *libraryPager) orderExpr(query *LibraryQuery) sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.column).Pad().WriteString(string(direction))
		if p.order.Field != DefaultLibraryOrder.Field {
			b.Comma().Ident(DefaultLibraryOrder.Field.column).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to Library.
func (l *LibraryQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...LibraryPaginateOption,
) (*LibraryConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newLibraryPager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if l, err = pager.applyFilter(l); err != nil {
		return nil, err
	}
	conn := &LibraryConnection{Edges: []*LibraryEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			c := l.Clone()
			c.ctx.Fields = nil
			if conn.TotalCount, err = c.Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}
	if l, err = pager.applyCursors(l, after, before); err != nil {
		return nil, err
	}
	limit := paginateLimit(first, last)
	if limit != 0 {
		l.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := l.collectField(ctx, limit == 1, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}
	l = pager.applyOrder(l)
	nodes, err := l.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// LibraryOrderField defines the ordering field of Library.
type LibraryOrderField struct {
	// Value extracts the ordering value from the given Library.
	Value    func(*Library) (ent.Value, error)
	column   string // field or computed.
	toTerm   func(...sql.OrderTermOption) library.OrderOption
	toCursor func(*Library) Cursor
}

// LibraryOrder defines the ordering of Library.
type LibraryOrder struct {
	Direction OrderDirection     `json:"direction"`
	Field     *LibraryOrderField `json:"field"`
}

// DefaultLibraryOrder is the default ordering of Library.
var DefaultLibraryOrder = &LibraryOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &LibraryOrderField{
		Value: func(l *Library) (ent.Value, error) {
			return l.ID, nil
		},
		column: library.FieldID,
		toTerm: library.ByID,
		toCursor: func(l *Library) Cursor {
			return Cursor{ID: l.ID}
		},
	},
}

// ToEdge converts Library into LibraryEdge.
func (l *Library) ToEdge(order *LibraryOrder) *LibraryEdge {
	if order == nil {
		order = DefaultLibraryOrder
	}
	return &LibraryEdge{
		Node:   l,
		Cursor: order.Field.toCursor(l),
	}
}

// PlaySessionEdge is the edge representation of PlaySession.
type PlaySessionEdge struct {
	Node   *PlaySession `json:"node"`
	Cursor Cursor       `json:"cursor"`
}

// PlaySessionConnection is the connection containing edges to PlaySession.
type PlaySessionConnection struct {
	Edges      []*PlaySessionEdge `json:"edges"`
	PageInfo   PageInfo           `json:"pageInfo"`
	TotalCount int                `json:"totalCount"`
}

func (c *PlaySessionConnection) build(nodes []*PlaySession, pager *playsessionPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *PlaySession
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *PlaySession {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *PlaySession {
			return nodes[i]
		}
	}
	c.Edges = make([]*PlaySessionEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &PlaySessionEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// PlaySessionPaginateOption enables pagination customization.
type PlaySessionPaginateOption func(*playsessionPager) error

// WithPlaySessionOrder configures pagination ordering.
func WithPlaySessionOrder(order *PlaySessionOrder) PlaySessionPaginateOption {
	if order == nil {
		order = DefaultPlaySessionOrder
	}
	o := *order
	return func(pager *playsessionPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultPlaySessionOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithPlaySessionFilter configures pagination filter.
func WithPlaySessionFilter(filter func(*PlaySessionQuery) (*PlaySessionQuery, error)) PlaySessionPaginateOption {
	return func(pager *playsessionPager) error {
		if filter == nil {
			return errors.New("PlaySessionQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type playsessionPager struct {
	reverse bool
	order   *PlaySessionOrder
	filter  func(*PlaySessionQuery) (*PlaySessionQuery, error)
}

func newPlaySessionPager(opts []PlaySessionPaginateOption, reverse bool) (*playsessionPager, error) {
	pager := &playsessionPager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultPlaySessionOrder
	}
	return pager, nil
}

func (p *playsessionPager) applyFilter(query *PlaySessionQuery) (*PlaySessionQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *playsessionPager) toCursor(ps *PlaySession) Cursor {
	return p.order.Field.toCursor(ps)
}

func (p *playsessionPager) applyCursors(query *PlaySessionQuery, after, before *Cursor) (*PlaySessionQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultPlaySessionOrder.Field.column, p.order.Field.column, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *playsessionPager) applyOrder(query *PlaySessionQuery) *PlaySessionQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(p.order.Field.toTerm(direction.OrderTermOption()))
	if p.order.Field != DefaultPlaySessionOrder.Field {
		query = query.Order(DefaultPlaySessionOrder.Field.toTerm(direction.OrderTermOption()))
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return query
}

func (p *playsessionPager) orderExpr(query *PlaySessionQuery) sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.column).Pad().WriteString(string(direction))
		if p.order.Field != DefaultPlaySessionOrder.Field {
			b.Comma().Ident(DefaultPlaySessionOrder.Field.column).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to PlaySession.
func (ps *PlaySessionQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...PlaySessionPaginateOption,
) (*PlaySessionConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newPlaySessionPager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if ps, err = pager.applyFilter(ps); err != nil {
		return nil, err
	}
	conn := &PlaySessionConnection{Edges: []*PlaySessionEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			c := ps.Clone()
			c.ctx.Fields = nil
			if conn.TotalCount, err = c.Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}
	if ps, err = pager.applyCursors(ps, after, before); err != nil {
		return nil, err
	}
	limit := paginateLimit(first, last)
	if limit != 0 {
		ps.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := ps.collectField(ctx, limit == 1, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}
	ps = pager.applyOrder(ps)
	nodes, err := ps.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// PlaySessionOrderField defines the ordering field of PlaySession.
type PlaySessionOrderField struct {
	// Value extracts the ordering value from the given PlaySession.
	Value    func(*PlaySession) (ent.Value, error)
	column   string // field or computed.
	toTerm   func(...sql.OrderTermOption) playsession.OrderOption
	toCursor func(*PlaySession) Cursor
}

// PlaySessionOrder defines the ordering of PlaySession.
type PlaySessionOrder struct {
	Direction OrderDirection         `json:"direction"`
	Field     *PlaySessionOrderField `json:"field"`
}

// DefaultPlaySessionOrder is the default ordering of PlaySession.
var DefaultPlaySessionOrder = &PlaySessionOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &PlaySessionOrderField{
		Value: func(ps *PlaySession) (ent.Value, error) {
			return ps.ID, nil
		},
		column: playsession.FieldID,
		toTerm: playsession.ByID,
		toCursor: func(ps *PlaySession) Cursor {
			return Cursor{ID: ps.ID}
		},
	},
}

// ToEdge converts PlaySession into PlaySessionEdge.
func (ps *PlaySession) ToEdge(order *PlaySessionOrder) *PlaySessionEdge {
	if order == nil {
		order = DefaultPlaySessionOrder
	}
	return &PlaySessionEdge{
		Node:   ps,
		Cursor: order.Field.toCursor(ps),
	}
}

// VideoEdge is the edge representation of Video.
type VideoEdge struct {
	Node   *Video `json:"node"`
	Cursor Cursor `json:"cursor"`
}

// VideoConnection is the connection containing edges to Video.
type VideoConnection struct {
	Edges      []*VideoEdge `json:"edges"`
	PageInfo   PageInfo     `json:"pageInfo"`
	TotalCount int          `json:"totalCount"`
}

func (c *VideoConnection) build(nodes []*Video, pager *videoPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *Video
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *Video {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *Video {
			return nodes[i]
		}
	}
	c.Edges = make([]*VideoEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &VideoEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// VideoPaginateOption enables pagination customization.
type VideoPaginateOption func(*videoPager) error

// WithVideoOrder configures pagination ordering.
func WithVideoOrder(order *VideoOrder) VideoPaginateOption {
	if order == nil {
		order = DefaultVideoOrder
	}
	o := *order
	return func(pager *videoPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultVideoOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithVideoFilter configures pagination filter.
func WithVideoFilter(filter func(*VideoQuery) (*VideoQuery, error)) VideoPaginateOption {
	return func(pager *videoPager) error {
		if filter == nil {
			return errors.New("VideoQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type videoPager struct {
	reverse bool
	order   *VideoOrder
	filter  func(*VideoQuery) (*VideoQuery, error)
}

func newVideoPager(opts []VideoPaginateOption, reverse bool) (*videoPager, error) {
	pager := &videoPager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultVideoOrder
	}
	return pager, nil
}

func (p *videoPager) applyFilter(query *VideoQuery) (*VideoQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *videoPager) toCursor(v *Video) Cursor {
	return p.order.Field.toCursor(v)
}

func (p *videoPager) applyCursors(query *VideoQuery, after, before *Cursor) (*VideoQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultVideoOrder.Field.column, p.order.Field.column, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *videoPager) applyOrder(query *VideoQuery) *VideoQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(p.order.Field.toTerm(direction.OrderTermOption()))
	if p.order.Field != DefaultVideoOrder.Field {
		query = query.Order(DefaultVideoOrder.Field.toTerm(direction.OrderTermOption()))
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return query
}

func (p *videoPager) orderExpr(query *VideoQuery) sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.column).Pad().WriteString(string(direction))
		if p.order.Field != DefaultVideoOrder.Field {
			b.Comma().Ident(DefaultVideoOrder.Field.column).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to Video.
func (v *VideoQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...VideoPaginateOption,
) (*VideoConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newVideoPager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if v, err = pager.applyFilter(v); err != nil {
		return nil, err
	}
	conn := &VideoConnection{Edges: []*VideoEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			c := v.Clone()
			c.ctx.Fields = nil
			if conn.TotalCount, err = c.Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}
	if v, err = pager.applyCursors(v, after, before); err != nil {
		return nil, err
	}
	limit := paginateLimit(first, last)
	if limit != 0 {
		v.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := v.collectField(ctx, limit == 1, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}
	v = pager.applyOrder(v)
	nodes, err := v.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// VideoOrderField defines the ordering field of Video.
type VideoOrderField struct {
	// Value extracts the ordering value from the given Video.
	Value    func(*Video) (ent.Value, error)
	column   string // field or computed.
	toTerm   func(...sql.OrderTermOption) video.OrderOption
	toCursor func(*Video) Cursor
}

// VideoOrder defines the ordering of Video.
type VideoOrder struct {
	Direction OrderDirection   `json:"direction"`
	Field     *VideoOrderField `json:"field"`
}

// DefaultVideoOrder is the default ordering of Video.
var DefaultVideoOrder = &VideoOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &VideoOrderField{
		Value: func(v *Video) (ent.Value, error) {
			return v.ID, nil
		},
		column: video.FieldID,
		toTerm: video.ByID,
		toCursor: func(v *Video) Cursor {
			return Cursor{ID: v.ID}
		},
	},
}

// ToEdge converts Video into VideoEdge.
func (v *Video) ToEdge(order *VideoOrder) *VideoEdge {
	if order == nil {
		order = DefaultVideoOrder
	}
	return &VideoEdge{
		Node:   v,
		Cursor: order.Field.toCursor(v),
	}
}
