// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
)

// CreateVideoInput represents a mutation input for creating videos.
type CreateVideoInput struct {
	Path      string
	CreatedAt *time.Time
}

// Mutate applies the CreateVideoInput on the VideoMutation builder.
func (i *CreateVideoInput) Mutate(m *VideoMutation) {
	m.SetPath(i.Path)
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
}

// SetInput applies the change-set in the CreateVideoInput on the VideoCreate builder.
func (c *VideoCreate) SetInput(i CreateVideoInput) *VideoCreate {
	i.Mutate(c.Mutation())
	return c
}
