// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/altierawr/vstreamer/ent/playsession"
	"github.com/altierawr/vstreamer/ent/predicate"
	"github.com/altierawr/vstreamer/ent/video"
)

// PlaySessionUpdate is the builder for updating PlaySession entities.
type PlaySessionUpdate struct {
	config
	hooks    []Hook
	mutation *PlaySessionMutation
}

// Where appends a list predicates to the PlaySessionUpdate builder.
func (psu *PlaySessionUpdate) Where(ps ...predicate.PlaySession) *PlaySessionUpdate {
	psu.mutation.Where(ps...)
	return psu
}

// SetVideoID sets the "video" edge to the Video entity by ID.
func (psu *PlaySessionUpdate) SetVideoID(id int) *PlaySessionUpdate {
	psu.mutation.SetVideoID(id)
	return psu
}

// SetNillableVideoID sets the "video" edge to the Video entity by ID if the given value is not nil.
func (psu *PlaySessionUpdate) SetNillableVideoID(id *int) *PlaySessionUpdate {
	if id != nil {
		psu = psu.SetVideoID(*id)
	}
	return psu
}

// SetVideo sets the "video" edge to the Video entity.
func (psu *PlaySessionUpdate) SetVideo(v *Video) *PlaySessionUpdate {
	return psu.SetVideoID(v.ID)
}

// Mutation returns the PlaySessionMutation object of the builder.
func (psu *PlaySessionUpdate) Mutation() *PlaySessionMutation {
	return psu.mutation
}

// ClearVideo clears the "video" edge to the Video entity.
func (psu *PlaySessionUpdate) ClearVideo() *PlaySessionUpdate {
	psu.mutation.ClearVideo()
	return psu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (psu *PlaySessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, psu.sqlSave, psu.mutation, psu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (psu *PlaySessionUpdate) SaveX(ctx context.Context) int {
	affected, err := psu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (psu *PlaySessionUpdate) Exec(ctx context.Context) error {
	_, err := psu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (psu *PlaySessionUpdate) ExecX(ctx context.Context) {
	if err := psu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (psu *PlaySessionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(playsession.Table, playsession.Columns, sqlgraph.NewFieldSpec(playsession.FieldID, field.TypeInt))
	if ps := psu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if psu.mutation.VideoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playsession.VideoTable,
			Columns: []string{playsession.VideoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(video.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := psu.mutation.VideoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playsession.VideoTable,
			Columns: []string{playsession.VideoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(video.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, psu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{playsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	psu.mutation.done = true
	return n, nil
}

// PlaySessionUpdateOne is the builder for updating a single PlaySession entity.
type PlaySessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlaySessionMutation
}

// SetVideoID sets the "video" edge to the Video entity by ID.
func (psuo *PlaySessionUpdateOne) SetVideoID(id int) *PlaySessionUpdateOne {
	psuo.mutation.SetVideoID(id)
	return psuo
}

// SetNillableVideoID sets the "video" edge to the Video entity by ID if the given value is not nil.
func (psuo *PlaySessionUpdateOne) SetNillableVideoID(id *int) *PlaySessionUpdateOne {
	if id != nil {
		psuo = psuo.SetVideoID(*id)
	}
	return psuo
}

// SetVideo sets the "video" edge to the Video entity.
func (psuo *PlaySessionUpdateOne) SetVideo(v *Video) *PlaySessionUpdateOne {
	return psuo.SetVideoID(v.ID)
}

// Mutation returns the PlaySessionMutation object of the builder.
func (psuo *PlaySessionUpdateOne) Mutation() *PlaySessionMutation {
	return psuo.mutation
}

// ClearVideo clears the "video" edge to the Video entity.
func (psuo *PlaySessionUpdateOne) ClearVideo() *PlaySessionUpdateOne {
	psuo.mutation.ClearVideo()
	return psuo
}

// Where appends a list predicates to the PlaySessionUpdate builder.
func (psuo *PlaySessionUpdateOne) Where(ps ...predicate.PlaySession) *PlaySessionUpdateOne {
	psuo.mutation.Where(ps...)
	return psuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (psuo *PlaySessionUpdateOne) Select(field string, fields ...string) *PlaySessionUpdateOne {
	psuo.fields = append([]string{field}, fields...)
	return psuo
}

// Save executes the query and returns the updated PlaySession entity.
func (psuo *PlaySessionUpdateOne) Save(ctx context.Context) (*PlaySession, error) {
	return withHooks(ctx, psuo.sqlSave, psuo.mutation, psuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (psuo *PlaySessionUpdateOne) SaveX(ctx context.Context) *PlaySession {
	node, err := psuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (psuo *PlaySessionUpdateOne) Exec(ctx context.Context) error {
	_, err := psuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (psuo *PlaySessionUpdateOne) ExecX(ctx context.Context) {
	if err := psuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (psuo *PlaySessionUpdateOne) sqlSave(ctx context.Context) (_node *PlaySession, err error) {
	_spec := sqlgraph.NewUpdateSpec(playsession.Table, playsession.Columns, sqlgraph.NewFieldSpec(playsession.FieldID, field.TypeInt))
	id, ok := psuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PlaySession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := psuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, playsession.FieldID)
		for _, f := range fields {
			if !playsession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != playsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := psuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if psuo.mutation.VideoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playsession.VideoTable,
			Columns: []string{playsession.VideoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(video.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := psuo.mutation.VideoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playsession.VideoTable,
			Columns: []string{playsession.VideoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(video.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PlaySession{config: psuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, psuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{playsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	psuo.mutation.done = true
	return _node, nil
}
