// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/altierawr/vstreamer/ent/predicate"
	"github.com/altierawr/vstreamer/ent/videocodec"
)

// VideoCodecDelete is the builder for deleting a VideoCodec entity.
type VideoCodecDelete struct {
	config
	hooks    []Hook
	mutation *VideoCodecMutation
}

// Where appends a list predicates to the VideoCodecDelete builder.
func (vcd *VideoCodecDelete) Where(ps ...predicate.VideoCodec) *VideoCodecDelete {
	vcd.mutation.Where(ps...)
	return vcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (vcd *VideoCodecDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, vcd.sqlExec, vcd.mutation, vcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (vcd *VideoCodecDelete) ExecX(ctx context.Context) int {
	n, err := vcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (vcd *VideoCodecDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(videocodec.Table, sqlgraph.NewFieldSpec(videocodec.FieldID, field.TypeInt))
	if ps := vcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, vcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	vcd.mutation.done = true
	return affected, err
}

// VideoCodecDeleteOne is the builder for deleting a single VideoCodec entity.
type VideoCodecDeleteOne struct {
	vcd *VideoCodecDelete
}

// Where appends a list predicates to the VideoCodecDelete builder.
func (vcdo *VideoCodecDeleteOne) Where(ps ...predicate.VideoCodec) *VideoCodecDeleteOne {
	vcdo.vcd.mutation.Where(ps...)
	return vcdo
}

// Exec executes the deletion query.
func (vcdo *VideoCodecDeleteOne) Exec(ctx context.Context) error {
	n, err := vcdo.vcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{videocodec.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (vcdo *VideoCodecDeleteOne) ExecX(ctx context.Context) {
	if err := vcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
