// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AudioCodecsColumns holds the columns for the "audio_codecs" table.
	AudioCodecsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "mime", Type: field.TypeString},
		{Name: "play_session_media_audio_codecs", Type: field.TypeInt, Nullable: true},
	}
	// AudioCodecsTable holds the schema information for the "audio_codecs" table.
	AudioCodecsTable = &schema.Table{
		Name:       "audio_codecs",
		Columns:    AudioCodecsColumns,
		PrimaryKey: []*schema.Column{AudioCodecsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "audio_codecs_play_session_media_audio_codecs",
				Columns:    []*schema.Column{AudioCodecsColumns[3]},
				RefColumns: []*schema.Column{PlaySessionMediaColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// AudioTracksColumns holds the columns for the "audio_tracks" table.
	AudioTracksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "nr_channels", Type: field.TypeInt},
		{Name: "channel_layout", Type: field.TypeString},
		{Name: "language", Type: field.TypeString, Nullable: true},
		{Name: "play_session_media_audio_tracks", Type: field.TypeInt},
	}
	// AudioTracksTable holds the schema information for the "audio_tracks" table.
	AudioTracksTable = &schema.Table{
		Name:       "audio_tracks",
		Columns:    AudioTracksColumns,
		PrimaryKey: []*schema.Column{AudioTracksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "audio_tracks_play_session_media_audio_tracks",
				Columns:    []*schema.Column{AudioTracksColumns[5]},
				RefColumns: []*schema.Column{PlaySessionMediaColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// LibrariesColumns holds the columns for the "libraries" table.
	LibrariesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "path", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// LibrariesTable holds the schema information for the "libraries" table.
	LibrariesTable = &schema.Table{
		Name:       "libraries",
		Columns:    LibrariesColumns,
		PrimaryKey: []*schema.Column{LibrariesColumns[0]},
	}
	// PlaySessionsColumns holds the columns for the "play_sessions" table.
	PlaySessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "current_time", Type: field.TypeInt, Nullable: true},
		{Name: "state", Type: field.TypeEnum, Enums: []string{"PLAYING", "PAUSED", "BUFFERING", "STOPPED"}, Default: "STOPPED"},
	}
	// PlaySessionsTable holds the schema information for the "play_sessions" table.
	PlaySessionsTable = &schema.Table{
		Name:       "play_sessions",
		Columns:    PlaySessionsColumns,
		PrimaryKey: []*schema.Column{PlaySessionsColumns[0]},
	}
	// PlaySessionMediaColumns holds the columns for the "play_session_media" table.
	PlaySessionMediaColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "resolutions", Type: field.TypeJSON},
		{Name: "play_session_media", Type: field.TypeInt, Unique: true},
		{Name: "video_play_session_medias", Type: field.TypeInt, Nullable: true},
	}
	// PlaySessionMediaTable holds the schema information for the "play_session_media" table.
	PlaySessionMediaTable = &schema.Table{
		Name:       "play_session_media",
		Columns:    PlaySessionMediaColumns,
		PrimaryKey: []*schema.Column{PlaySessionMediaColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "play_session_media_play_sessions_media",
				Columns:    []*schema.Column{PlaySessionMediaColumns[2]},
				RefColumns: []*schema.Column{PlaySessionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "play_session_media_videos_play_session_medias",
				Columns:    []*schema.Column{PlaySessionMediaColumns[3]},
				RefColumns: []*schema.Column{VideosColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// PlaybackClientsColumns holds the columns for the "playback_clients" table.
	PlaybackClientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "is_buffered", Type: field.TypeBool, Default: false},
		{Name: "play_session_clients", Type: field.TypeInt, Nullable: true},
	}
	// PlaybackClientsTable holds the schema information for the "playback_clients" table.
	PlaybackClientsTable = &schema.Table{
		Name:       "playback_clients",
		Columns:    PlaybackClientsColumns,
		PrimaryKey: []*schema.Column{PlaybackClientsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "playback_clients_play_sessions_clients",
				Columns:    []*schema.Column{PlaybackClientsColumns[2]},
				RefColumns: []*schema.Column{PlaySessionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// StreamsColumns holds the columns for the "streams" table.
	StreamsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "width", Type: field.TypeInt},
		{Name: "height", Type: field.TypeInt},
		{Name: "container", Type: field.TypeString},
		{Name: "segment_duration", Type: field.TypeInt},
		{Name: "quality", Type: field.TypeEnum, Enums: []string{"maximum", "medium", "low"}},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"direct", "remux", "video_transcode", "audio_transcode", "full_transcode"}},
		{Name: "audio_codec_streams", Type: field.TypeInt, Nullable: true},
		{Name: "video_codec_streams", Type: field.TypeInt, Nullable: true},
	}
	// StreamsTable holds the schema information for the "streams" table.
	StreamsTable = &schema.Table{
		Name:       "streams",
		Columns:    StreamsColumns,
		PrimaryKey: []*schema.Column{StreamsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "streams_audio_codecs_streams",
				Columns:    []*schema.Column{StreamsColumns[7]},
				RefColumns: []*schema.Column{AudioCodecsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "streams_video_codecs_streams",
				Columns:    []*schema.Column{StreamsColumns[8]},
				RefColumns: []*schema.Column{VideoCodecsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// VideosColumns holds the columns for the "videos" table.
	VideosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "path", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "library_videos", Type: field.TypeInt, Nullable: true},
	}
	// VideosTable holds the schema information for the "videos" table.
	VideosTable = &schema.Table{
		Name:       "videos",
		Columns:    VideosColumns,
		PrimaryKey: []*schema.Column{VideosColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "videos_libraries_videos",
				Columns:    []*schema.Column{VideosColumns[3]},
				RefColumns: []*schema.Column{LibrariesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// VideoCodecsColumns holds the columns for the "video_codecs" table.
	VideoCodecsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "mime", Type: field.TypeString},
		{Name: "dynamic_range", Type: field.TypeEnum, Enums: []string{"sdr", "hdr"}},
		{Name: "play_session_media_video_codecs", Type: field.TypeInt, Nullable: true},
	}
	// VideoCodecsTable holds the schema information for the "video_codecs" table.
	VideoCodecsTable = &schema.Table{
		Name:       "video_codecs",
		Columns:    VideoCodecsColumns,
		PrimaryKey: []*schema.Column{VideoCodecsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "video_codecs_play_session_media_video_codecs",
				Columns:    []*schema.Column{VideoCodecsColumns[4]},
				RefColumns: []*schema.Column{PlaySessionMediaColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// AudioTrackCodecsColumns holds the columns for the "audio_track_codecs" table.
	AudioTrackCodecsColumns = []*schema.Column{
		{Name: "audio_track_id", Type: field.TypeInt},
		{Name: "audio_codec_id", Type: field.TypeInt},
	}
	// AudioTrackCodecsTable holds the schema information for the "audio_track_codecs" table.
	AudioTrackCodecsTable = &schema.Table{
		Name:       "audio_track_codecs",
		Columns:    AudioTrackCodecsColumns,
		PrimaryKey: []*schema.Column{AudioTrackCodecsColumns[0], AudioTrackCodecsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "audio_track_codecs_audio_track_id",
				Columns:    []*schema.Column{AudioTrackCodecsColumns[0]},
				RefColumns: []*schema.Column{AudioTracksColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "audio_track_codecs_audio_codec_id",
				Columns:    []*schema.Column{AudioTrackCodecsColumns[1]},
				RefColumns: []*schema.Column{AudioCodecsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AudioCodecsTable,
		AudioTracksTable,
		LibrariesTable,
		PlaySessionsTable,
		PlaySessionMediaTable,
		PlaybackClientsTable,
		StreamsTable,
		VideosTable,
		VideoCodecsTable,
		AudioTrackCodecsTable,
	}
)

func init() {
	AudioCodecsTable.ForeignKeys[0].RefTable = PlaySessionMediaTable
	AudioTracksTable.ForeignKeys[0].RefTable = PlaySessionMediaTable
	PlaySessionMediaTable.ForeignKeys[0].RefTable = PlaySessionsTable
	PlaySessionMediaTable.ForeignKeys[1].RefTable = VideosTable
	PlaybackClientsTable.ForeignKeys[0].RefTable = PlaySessionsTable
	StreamsTable.ForeignKeys[0].RefTable = AudioCodecsTable
	StreamsTable.ForeignKeys[1].RefTable = VideoCodecsTable
	VideosTable.ForeignKeys[0].RefTable = LibrariesTable
	VideoCodecsTable.ForeignKeys[0].RefTable = PlaySessionMediaTable
	AudioTrackCodecsTable.ForeignKeys[0].RefTable = AudioTracksTable
	AudioTrackCodecsTable.ForeignKeys[1].RefTable = AudioCodecsTable
}
