// Code generated by ent, DO NOT EDIT.

package playbackclient

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/altierawr/vstreamer/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PlaybackClient {
	return predicate.PlaybackClient(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PlaybackClient {
	return predicate.PlaybackClient(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PlaybackClient {
	return predicate.PlaybackClient(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PlaybackClient {
	return predicate.PlaybackClient(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PlaybackClient {
	return predicate.PlaybackClient(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PlaybackClient {
	return predicate.PlaybackClient(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PlaybackClient {
	return predicate.PlaybackClient(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PlaybackClient {
	return predicate.PlaybackClient(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PlaybackClient {
	return predicate.PlaybackClient(sql.FieldLTE(FieldID, id))
}

// IsBuffered applies equality check predicate on the "is_buffered" field. It's identical to IsBufferedEQ.
func IsBuffered(v bool) predicate.PlaybackClient {
	return predicate.PlaybackClient(sql.FieldEQ(FieldIsBuffered, v))
}

// IsBufferedEQ applies the EQ predicate on the "is_buffered" field.
func IsBufferedEQ(v bool) predicate.PlaybackClient {
	return predicate.PlaybackClient(sql.FieldEQ(FieldIsBuffered, v))
}

// IsBufferedNEQ applies the NEQ predicate on the "is_buffered" field.
func IsBufferedNEQ(v bool) predicate.PlaybackClient {
	return predicate.PlaybackClient(sql.FieldNEQ(FieldIsBuffered, v))
}

// HasSession applies the HasEdge predicate on the "session" edge.
func HasSession() predicate.PlaybackClient {
	return predicate.PlaybackClient(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SessionTable, SessionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionWith applies the HasEdge predicate on the "session" edge with a given conditions (other predicates).
func HasSessionWith(preds ...predicate.PlaySession) predicate.PlaybackClient {
	return predicate.PlaybackClient(func(s *sql.Selector) {
		step := newSessionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PlaybackClient) predicate.PlaybackClient {
	return predicate.PlaybackClient(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PlaybackClient) predicate.PlaybackClient {
	return predicate.PlaybackClient(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PlaybackClient) predicate.PlaybackClient {
	return predicate.PlaybackClient(sql.NotPredicates(p))
}
